config/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('ohb.urls')),
    path('', include('user.urls')),
    path('', include('shift.urls')),

    path('admin/', admin.site.urls),
   
]

ohb/urls.py
from django.urls import path
from . import views

app_name='ohb'

urlpatterns = [
    # path('top/',views.Top.as_view(), name='top'),
    path('create/',views.ItemsCreateView.as_view(), name='create'),
    path('list/', views.ItemsListView.as_view(), name='list'),
    path('form/', views.Items_View.as_view(), name='form'),
    path('form/<int:year>/<int:month>/<int:day>/', views.Items_View.as_view(), name='form'),
    path('week_list/', views.Create_los_ListView.as_view(), name='week_list'),
    path('week_list/<int:year>/<int:month>/', views.Create_los_ListView.as_view(), name='week_list'),
    #path('buy/', views.Buy＿View.as_view(), name='buy'),
    #path('buy/<int:year>/<int:month>/', views.Buy＿View.as_view(), name='buy'),
    path('graph/', views.Graph_View.as_view(), name='graph'),
    path('graph/<int:id>/<int:year>/<int:month>/<int:day>', views.Graph_View.as_view(), name='graph'),
    path('item_no/', views.item_No_Views.as_view(), name='item_no'),
    


    #path('form/', views.make_test_modelformset, name='form'),
    
]

user/urls.py
from django.urls import path
from . import views
from .views import login_view

app_name='user'

urlpatterns = [
    # ... other URL patterns
   # path('', views.login_view, name='login'),
    #path('', views.CustomLoginView.as_view(), name='login'),
    path('', views.login_view, name='login'), 
    path('top/',views.Top.as_view(),name='top'),
    path('<int:pk>no/',views.MemberNo.as_view(),name='no'),
   

]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    types = (
        ('1', 'EDW'),
        ('2', 'OHB'),
    )

    user_id = models.CharField('ID', max_length=15, unique=True)
    user_name=models.CharField('名前', max_length=15, unique=True)
    job = models.CharField("タイプ", max_length=15, choices=types, blank=True, default='1')
    user_no = models.IntegerField('No', default=0)

user/forms.py
# forms.py

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import CustomUser


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(max_length=254, label='User ID', widget=forms.TextInput(attrs={'autofocus': True}))



class MemberNoForm(forms.ModelForm):
    class Meta:
        model=CustomUser
        fields =('user_no',)

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.views import generic
import logging
from django.shortcuts import render, redirect
from django.contrib.auth import login
from . import mixins
from .models import CustomUser
from .forms import MemberNoForm

User = get_user_model()

logger = logging.getLogger(__name__)

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')  # フォームからユーザー名を取得
        password = request.POST.get('password')  # フォームからパスワードを取得

        # ユーザーの認証を試行
        logger.debug(f"Received username: {username}, password: {password}")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            # 認証に成功した場合
            login(request, user)  # ユーザーをログインさせる
            user_authenticated_successfully = True
            return redirect('top/')  # ログイン後のページにリダイレクト
        else:
    # 認証に失敗した場合
            messages.error(request, 'ユーザー認証に失敗しました。正しいユーザー名とパスワードを入力してください。')
            user_authenticated_successfully = False
            return render(request, 'login.html', {'authentication_failed': True})

        # GETリクエストを処理する場合
    else:
        user_authenticated_successfully = False  # 初期状態では認証は成功していない
        return render(request, 'login.html', {'authentication_failed': False})

class Top(generic.TemplateView):
    template_name = 'top.html'

class MemberNo(generic.View,mixins.NoMixin):
    model=CustomUser
    form_class=MemberNoForm
    template_name='no.html'

    def get(self, request, **kwargs):
        pk = self.kwargs['pk']
        context = self.get_member_no()

        return render(request, self.template_name, context)

    def post(self, request, **kwargs):

        context = self.get_member_no()
        formset = context['formset']

        if formset.is_valid():
            instances = formset.save(commit=False)
            for customuser in instances:
                customuser.save()
                pk=1
            return redirect('user:top')

        return render(request, self.template_name, context)



# User = get_user_model()

# def login_view(request):
#     if request.method == 'POST':
#         user_id = request.POST['user_id']
#         password = request.POST['password']

#         user = authenticate(user_id=user_id, password=password)
#         if user is not None:
#             login(request, user)
#             return redirect('ohb/top.html')  # ログイン成功後のリダイレクト先を適宜設定
#         else:
#             messages.error(request, 'Invalid user_id or password.')

#     return render(request, 'user/login.html')

# @login_required
# def home_view(request):
#     return render(request, 'ohb/top.html')


# views.py

user/templates/base.html
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

<head>
    
  <html lang="ja">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  
    </head>
 
    <nav class="navbar navbar-dark bg-dark  navbar-expand-lg " >
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
           

              
              

            <li class="nav-item">
              <a class="nav-link" href="{% url 'ohb:list'%}">&nbsp;&nbsp;&nbsp;List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ohb:create'%}">作成</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ohb:form'%}">カウント</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ohb:week_list'%}">作成・ロスLIST</a>
            </li>  
            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ohb:item_no'%}">NO</a>
            </li>  
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:login'%}">Login</a>
            </li> 
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:no'%}">no</a>
            </li> 


        </div>
      </nav>
   
    
      
    </div>
  </nav>
  
      
     
            {% block content %}
        
        
            {% endblock %}
          </div>
        </div>
      </main>

       

      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

user/templates/login.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<body>
    <div id="login">
        <h3 class="text-center text-white pt-5">Login form</h3>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form id="login-form" class="form" action="{% url 'user:login' %}" method="POST">
                            <h3 class="text-center text-info">Login</h3>
                            <div class="form-group">
                                <label for="username" class="text-info">User ID:</label><br>
                                <input type="text" id="username" name="username" required class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password" class="text-info">Password:</label><br>
                                <input type="password" id="password" name="password" required class="form-control">
                            </div>
                            {% if messages %}
                            <ul class="errorlist">
                                {% for message in messages %}
                                <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                            {% endif %}
                            <div class="form-group">
                                <input type="submit" name="submit" class="btn btn-info btn-md" value="submit">
                            </div>{% csrf_token %}
                            
                            <div id="register-link" class="text-right">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% load static %}


user/templates/no.html
{% extends "shift/shift_base.html" %}


{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}{% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
 
   
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            
              <a class="nav-item nav-link" href="{% url 'user:no' 1 %}">
              EDW</a>
              <a class="nav-item nav-link" href="{% url 'user:no' 2 %}">
                OHB</a>
                            

          </div>
      </div>
    </div>
    
    <span class="navbar-text">
      <small>
      在籍
      
    </small>
    </span>
  </nav>

<h3></h3>

<p>シフトの並び順を決めてください。</p>
<p>数字が大きい順ではなく、11＜2　101＜2となります。</p>
<p>お勧め設定　今後在籍が上下することを考えて下記の設定がお勧めです</p>

<p>名簿や希望シフト、シフト出力の並び順はここでの設定に依存します。</p>
</p>
<form action="" method="POST">
    
    {{ formset.management_form }}
    <table class="table table-bordered">
        <tr>
            
            
            <th>User</th>
            <th>順番</th>
        </tr>

        {% for form in formset %}
        <tr>
          <!-- <label for="{{ form.item_no.id_for_label }}"> {{ form.instance.item_name }}</label> -->
         
          <td>{{ form.instance.user_name }}</td>
          <td> {{ form.user_no }}</td>
          <td> {{ form.id }}</td>



</tr>


{%endfor%}
</table>

{% csrf_token %}
<button type="submit" class="btn btn-primary">送信</button>
</form>

{% endblock %}

user/templates/top.html


{% extends "ohb/base.html" %}
{% block content %}

----------------information-----------------------



{% endblock %}



