config/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('ohb.urls')),
    path('', include('user.urls')),
    path('', include('shift.urls')),

    path('admin/', admin.site.urls),
   
]

ohb/urls.py
from django.urls import path
from . import views

app_name='ohb'

urlpatterns = [
    # path('top/',views.Top.as_view(), name='top'),
    path('create/',views.ItemsCreateView.as_view(), name='create'),
    path('list/', views.ItemsListView.as_view(), name='list'),
    path('form/', views.Items_View.as_view(), name='form'),
    path('form/<int:year>/<int:month>/<int:day>/', views.Items_View.as_view(), name='form'),
    path('week_list/', views.Create_los_ListView.as_view(), name='week_list'),
    path('week_list/<int:year>/<int:month>/', views.Create_los_ListView.as_view(), name='week_list'),
    #path('buy/', views.Buy＿View.as_view(), name='buy'),
    #path('buy/<int:year>/<int:month>/', views.Buy＿View.as_view(), name='buy'),
    path('graph/', views.Graph_View.as_view(), name='graph'),
    path('graph/<int:id>/<int:year>/<int:month>/<int:day>', views.Graph_View.as_view(), name='graph'),
    path('item_no/', views.item_No_Views.as_view(), name='item_no'),
    


    #path('form/', views.make_test_modelformset, name='form'),
    
]

shift/urls.py
from django.urls import path
from . import views

app_name = 'shift'

urlpatterns = [
    path('shift_top/',views.Shift_top.as_view(),name='shift_top'),
    path('shift_list/<int:job_pk>/', views.Shift_OutputView.as_view(), name='shift_list'),
    path('shift_list/<int:job_pk>/<int:year>/<int:month>/<int:day>/', views.Shift_OutputView.as_view(), name='shift_list'),
    path('user/<int:user_pk>/shift_confirmation/', views.Shift_ConfirmationView.as_view(), name='shift_confirmation'),
    path('user/<int:user_pk>/shift_confirmation/<int:year>/<int:month>/<int:day>/',views.Shift_ConfirmationView.as_view(),name='shift_confirmation'),

    path('shift_csv/<int:job_pk>/<int:year>/<int:month>/<int:day>/', views.Shift_csv.as_view(), name='shift_csv'),
    path('shift_csv/<int:job_pk>/', views.Shift_csv.as_view(), name='shift_csv'),
    path(
        'user/<int:user_pk>/submission_schedule/',
        views.SubmissionView.as_view(), name='submission_schedule'
    ),
    path(
        'user/<int:user_pk>/submission_schedule/<int:year>/<int:month>/<int:day>/',
        views.SubmissionView.as_view(), name='submission_schedule'
    ),
]

user/urls.py
from django.urls import path
from . import views
from .views import login_view

app_name='user'

urlpatterns = [
    # ... other URL patterns
   # path('', views.login_view, name='login'),
    #path('', views.CustomLoginView.as_view(), name='login'),
    path('', views.login_view, name='login'), 
    path('top/',views.Top.as_view(),name='top'),
    path('<int:pk>no/',views.MemberNo.as_view(),name='no'),
   

]

ohb/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse_lazy,reverse

class Ohb_items(models.Model):

    types= (
        ('1','食パン'),      
        ('2','クロワッサン'),
        ('3','リュスティック'),
        ('4','パイ'),
        ('5','タルティーヌ'),
        ('6','その他'),
    )
    item_name = models.CharField('商品名',max_length=50,blank=False,)
    item_price = models.IntegerField('価格',default=0)
    item_type = models.CharField("タイプ", max_length=15,choices=types, blank=True,default=1)
    item_no= models.CharField(max_length=3,blank=True)

    def __str__(self):
        return self.item_name
    #def get_absolute_url(self):
    #    return reverse('ohb:item', args=[str(self.pk),])
    

class Items_Counts(models.Model):
    item = models.ForeignKey(Ohb_items,on_delete=models.CASCADE)
    item_create = models.IntegerField('作成数',default=0)
    item_los = models.IntegerField('ロス',default=0)
    date = models.DateField('日付')

    def __str__(self):
        return f"{self.item}{self.date}"
    
    def save(self, *args, **kwargs):
        # デフォルトの値をセット
        if self.item_create is None:
            self.item_create = 0
        if self.item_los is None:
            self.item_los = 0

        # 親クラスの save() メソッドを呼び出す
        super().save(*args, **kwargs)
 





ohb/forms.py
from django import forms
from .models import Ohb_items,Items_Counts


class items_CountsForm(forms.ModelForm):


    class Meta:
        model = Items_Counts
        fields=('item_create','item_los','item','date')
        #fields=('item_create','date')


        widgets = {
            # 'summary': forms.TextInput(attrs={
                # 'class': 'form-control',
            # }),
            'date': forms.HiddenInput,
            'item': forms.HiddenInput,
        }
        
class NoForm(forms.ModelForm):
    class Meta:
        model=Ohb_items
        fields =('item_no',)

        

ohb/views.py
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic.edit import FormView
from django import forms
from django.http import HttpResponse,HttpResponseRedirect
from django.views import generic
from ohb.models import Ohb_items,Items_Counts
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.urls import reverse
from .forms import items_CountsForm,NoForm
from . import mixins
import datetime
from django.utils import timezone
import pandas as pd
from django_pandas.io import read_frame
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import numpy as np


class ItemsCreateView(CreateView):
    model = Ohb_items
    template_name= 'ohb/create.html'
    fields = "__all__"
    success_url = reverse_lazy('ohb:create')

class ItemsListView(ListView):
    model = Ohb_items
    template_name= 'ohb/items_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        items = Ohb_items.objects.all().order_by('item_type')

        db=read_frame(items)
        
        df_context = pd.DataFrame(columns=['item_name', 'item_price', 'item_type'])
        df_context['item_name']=db['item_name']
        df_context['item_price']=db['item_price']
        df_context['item_type']=db['item_type']
        context['df_context'] = df_context
        #context['i']=items
        return context
    
class Create_los_ListView(ListView,mixins.Item_create_losMixin):
    model = Items_Counts
    template_name= 'ohb/week_list.html'
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['date']=self.get_date()
        date=self.get_date()
        for a,n in date:
            month_ago=a.month-1
            month_next=a.month+1
            year_ago=a.year-1
            year_next=a.year+1
            year=a.year
            month=a.month
            day=a.day
        #12月と1月の年が変わるタイミングの処理
        if month_ago ==0:
            month_ago=12
        else:
            year_ago=year
        if month_next==13:
            month_next=1
            pass
        else:
            year_next=year
        context['day']=day
        context['year']=year
        context['month']=month
        context['month_ago']=month_ago
        context['month_next']=month_next
        context['year_ago']=year_ago
        context['year_next']=year_next
        df_context=self.create_list()
        context['df_context']=df_context
        return context

class Buy_View(Create_los_ListView,mixins.Item_create_losMixin):
    model = Items_Counts
    template_name= 'ohb/buy.html'
    date_field = 'date'
        
    def get_context(self, **kwargs):
        context = self.get_context_data()
        df_context=self.get_buy_date()
        context.update(df_context)
        #context['df_context']=df_context


        return context
        



# class Top(generic.TemplateView):
#     template_name = 'ohb/top.html'

class Items_View(generic.View,mixins.Items_Mixin):
    model=Items_Counts
    form_class=items_CountsForm
    template_name='ohb/form.html'
    date_field = 'date'

    def get(self, request, **kwargs):
        #contextはフォームセットが入っている、day_contextは日付関連が入っている、これを纏める為のupdate
        context = self.get_count()
        day_context=self.get_count_day()
        context.update(day_context)

        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        context = self.get_count()
        formset = context['formset']
        if formset.is_valid():
            instances = formset.save(commit=False)
            print(7878787878)
            for aa in instances:
                item = aa.item
                item_create=aa.item_create
                item_los=aa.item_los
                date=aa.date

                aa.save()
                item.save()
            return redirect('list')
        if not formset.is_valid():
            print(formset.errors)
        day_context=self.get_count_day()
        context.update(day_context)
        return render(request, self.template_name, context)

class Graph_View(generic.View,mixins.Graph_Item_Mixin):
    model=Items_Counts
    template_name='ohb/graph.html'
    date_field = 'date'

    def get(self, request, **kwargs):
        #graph_image = self.get_item_id()
        context=self.get_item_id()
        # context = {
        #     'graph_image': graph_image
        # }
        #context['graph_image']=graph_image
        #context['today']=datetime.datetime.now().day
        return  render(request, self.template_name, context)
    
class item_No_Views(generic.View,mixins.NoMixin):
    model=Ohb_items
    form_class=NoForm
    template_name='ohb/item_no.html'

    def get(self, request, **kwargs):
        context = self.get_item_no()

        return render(request, self.template_name, context)

    def post(self, request, **kwargs):

        context = self.get_item_no()
        formset = context['formset']
        if formset.is_valid():
            instances = formset.save(commit=False)
            for a in instances:
                a.save()
                
            return redirect('item_no')
        if not formset.is_valid():
            print(formset.errors)
            
        return render(request, self.template_name, context)

ohb/templates/ohb/a.html
{% for a,b in date %}
<td>{{ a.day }}日 <small>({{b}})</small></td>
{% if b == "日" %}

<td>  <span style="color: #F00;">{{ a.day }}日 <small>({{b}})</small></span></td>

{% elif b == "土" %}

<td><span style="color:#0000FF">{{ a.day }}日 <small>({{b}})</small></span></td>

{% else %}
<td> <small>{{ a.day }}日 <small>({{b}})</small></td>

       {% endif %} {% endfor %}

ohb/templates/ohb/base.html
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

<head>
    
  <html lang="ja">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  
    </head>
 
    <nav class="navbar navbar-dark bg-dark  navbar-expand-lg " >
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
           

              
              

            <li class="nav-item">
              <a class="nav-link" href="{% url 'ohb:list'%}">&nbsp;&nbsp;&nbsp;List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ohb:create'%}">作成</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ohb:form'%}">カウント</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ohb:week_list'%}">作成・ロスLIST</a>
            </li>  
            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ohb:item_no'%}">NO</a>
            </li>  
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:login'%}">login</a>
            </li> 
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:no' 1 %}">no</a>
            </li> 
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shift:shift_top'  %}">shift</a>
            </li> 


        </div>
      </nav>
   
    
      
    </div>
  </nav>
  
      
     
            {% block content %}
        
        
            {% endblock %}
          </div>
        </div>
      </main>

       

      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

ohb/templates/ohb/buy.html
{% extends "ohb/base.html" %}
{% block content %}


<div class="table-responsive">
  <table class="table table-bordered table-sm">

        <thead>
            <td><a  href="{% url 'buy' year_ago month_ago %}">前<<<</a>　　　　　{{year}}年{{month}}月　　販売数（ロス）　　　<a href="{% url 'buypip install matplotlib' year_next month_next  %}">>>>次</a></td>
         
        </thead>


      <table class="table table-striped table-bordered table-hover">
            <tr>
                <td>index</td>
                {% for a,b in date %}
                {% if b == "日" %}
                
                <td>{{ a.day }}日<span style="color: #F00;"> <small>({{b}})</small></span></td>
                
                {% elif b == "土" %}
                
                <td>{{ a.day }}日<span style="color:#0000FF"> <small>({{b}})</small></span></td>
                
                {% else %}
                <td> {{ a.day }}日 <small>({{b}})</small></td>
                
                       {% endif %} {% endfor %}
                                
            </tr>
            {% for index, values in df_context.iterrows %}
                <tr>
                    <th style="width: 500px;">{{ index }} 　　　　　　　　　　　　　　   </th>
                    {% for value in values %}
                        <td>{{ value }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>


      {% endblock %}

ohb/templates/ohb/create.html

{% extends "ohb/base.html" %}
{% block content %}

<head>
    <html lang="ja">
      <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="#" >
    
       <head>








<form method="post">{% csrf_token %}
  <p>新アイテムの登録</p>
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

ohb/templates/ohb/form.html
{% extends "ohb/base.html" %}
{% block content %}


<!DOCTYPE html>
<html lang="en">
<head>
  
        <a  href="{% url 'ohb:form' year_ago month_ago daya %}">前<<<</a>　　　{{year}}年{{month}}月{{day}}日　　　
        {% if today == day %}

        {%else%}
        
        <a href="{% url 'ohb:form' year_next month_next dayb %}">>>>次</a>
      
        {%endif%}

    <form action="" method="POST">
        {{ formset.management_form }}
        <table class="table table-bordered">
            
        <tr>
            <th>店舗</th>
            
            <th>作成数</th>
            <th>廃棄</th>
        </tr>
        

{% for aa,k in zip_date  %}

<tr>
<td>{{k.item}}{{k.id}}   {{aa}}</td><td>{{k.item_create}}</td><td>{{k.item_los}}</td>{{k.date}}
    
    </tr>
   
    {%endfor%}
    </table>{% csrf_token %}
    <button type="submit" class="btn btn-primary">送信</button>
    </form>
    

    
{% endblock %}

ohb/templates/ohb/graph.html
{% extends "ohb/base.html" %}
{% block content %}


{% load static %}
<style>
    .left-align-image {
      float: left; /* 画像を左寄せにするためのスタイル */
      margin-right: 10px; /* 画像と周囲の余白を調整 */
    }
  </style>  

        
   
        <img src="data:image/png;base64,{{ graph_image }}" alt="Graph Image"class="left-align-image">

        <table class="table table-striped table-bordered table-hover">
            <tr><th></th>
        {% for a in days %}
        <th>{{a}}日</th>
        {%endfor%}
    </tr>
    <tr>
    <th>作成数</th>
        {% for a in item_create %}
        <td>{{a}}</td>
        {%endfor%}
    </tr>
    <th>ロス</th>
    {% for a in item_los %}
    <td>{{a}}</td>
    {%endfor%}
    </tr>
    <th>平均値</th>
    {% for a in ave %}
    <td>{{a}}</td>
    {%endfor%}
</tr>


        
        {% endblock %}
      

ohb/templates/ohb/item_no.html
{% extends "ohb/base.html" %}
{% block content %}
<p>数字が大きい順ではなく、11＜2　101＜2となります。</p>
<form action="" method="POST">
    {{ formset.management_form }}
    <div class="form-group">
    <table class="table table-bordered">
        <tr>
            <th>Item</th>
            <th>No</th>
            
        </tr>

        {% for form in formset %}
        <tr>
          <!-- <label for="{{ form.item_no.id_for_label }}"> {{ form.instance.item_name }}</label> -->
         
          <td>{{ form.instance.item_name }}</td>
          <td> {{ form.item_no }}</td>
          <td> {{ form.id }}</td>
        </tr>
      {% endfor %}</div>
</table>

{% csrf_token %}
<button type="submit" class="btn btn-primary">送信</button>
</form>




{% endblock %}

ohb/templates/ohb/items_list.html
{% extends "ohb/base.html" %}
{% block content %}


<div class="table-responsive">
  <table class="table table-bordered table-sm">
        <thead>

          
          
         
        </thead>
      
        
      <tbody>
          {% for a in i %}
         
            <tr>
            <td>{{a.item_name}}</td>
            <td>{{a.item_price}}円</td>
            </tr>    

      </tbody> {% endfor %}
      </table></div>
      <a href="{% url 'ohb:create' %}">登録ページ</a>

      <table class="table table-striped table-bordered table-hover">
            <tr>
                <td>index</td>
                {% for a in df_context %}
                    <td>{{ a }}</td>
                {% endfor %}
            </tr>
            {% for index, values in df_context.iterrows %}
                <tr>
                    <th>{{ index }}</th>
                    {% for value in values %}
                        <td>{{ value }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>


      {% endblock %}

ohb/templates/ohb/top.html


{% extends "ohb/base.html" %}
{% block content %}

----------------information-----------------------



{% endblock %}





ohb/templates/ohb/week_list.html
{% extends "ohb/base.html" %}
{% block content %}


<div class="table-responsive">
  <table class="table table-bordered table-sm">

        <thead>
            <td><a  href="{% url 'ohb:week_list' year_ago month_ago %}">前<<<</a>　　　　　{{year}}年{{month}}月　　　　　<a href="{% url 'ohb:week_list' year_next month_next  %}">>>>次</a></td>
          
         
        </thead>


      <table class="table table-striped table-bordered table-hover">
            <tr>
                <td>index</td>
                {% for a,b in date %}
                {% if b == "日" %}
                
                <td>{{ a.day }}日<span style="color: #F00;"> <small>({{b}})</small></span></td>
                
                {% elif b == "土" %}
                
                <td>{{ a.day }}日<span style="color:#0000FF"> <small>({{b}})</small></span></td>
                
                {% else %}
                <td> {{ a.day }}日 <small>({{b}})</small></td>
                
                       {% endif %} {% endfor %}
                                
            </tr>
            {% for index, values in df_context.iterrows %}
                <tr>
                    {% if index.id == None %}
                    {% with new_id=100 %}
                    <th><a href="{% url 'ohb:graph' new_id year month day %}">
                      {{ index }} 　　　　　　　　　　　　　　
                    </a></th>
                    {%endwith%}
                    {%else%}
                    <th><a href="{% url 'ohb:graph' index.id year month day %}">
                    {{ index }} 　　　　　　　　　　　　　　  </a> </th>
                    {%endif%}
                    {% for value in values %}
                        <td>{{ value }}</td>
                       
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>


      {% endblock %}