config/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('ohb.urls')),
    path('', include('user.urls')),
    path('', include('shift.urls')),

    path('admin/', admin.site.urls),
   
]

ohb/urls.py
from django.urls import path
from . import views

app_name='ohb'

urlpatterns = [
    # path('top/',views.Top.as_view(), name='top'),
    path('create/',views.ItemsCreateView.as_view(), name='create'),
    path('list/', views.ItemsListView.as_view(), name='list'),
    path('form/', views.Items_View.as_view(), name='form'),
    path('form/<int:year>/<int:month>/<int:day>/', views.Items_View.as_view(), name='form'),
    path('week_list/', views.Create_los_ListView.as_view(), name='week_list'),
    path('week_list/<int:year>/<int:month>/', views.Create_los_ListView.as_view(), name='week_list'),
    #path('buy/', views.Buy＿View.as_view(), name='buy'),
    #path('buy/<int:year>/<int:month>/', views.Buy＿View.as_view(), name='buy'),
    path('graph/', views.Graph_View.as_view(), name='graph'),
    path('graph/<int:id>/<int:year>/<int:month>/<int:day>', views.Graph_View.as_view(), name='graph'),
    path('item_no/', views.item_No_Views.as_view(), name='item_no'),
    


    #path('form/', views.make_test_modelformset, name='form'),
    
]

shift/urls.py
from django.urls import path
from . import views

app_name = 'shift'

urlpatterns = [
    path('shift_top/',views.Shift_top.as_view(),name='shift_top'),
    path('shift_list/<int:job_pk>/', views.Shift_OutputView.as_view(), name='shift_list'),
    path('shift_list/<int:job_pk>/<int:year>/<int:month>/<int:day>/', views.Shift_OutputView.as_view(), name='shift_list'),
    path('user/<int:user_pk>/shift_confirmation/', views.Shift_ConfirmationView.as_view(), name='shift_confirmation'),
    path('user/<int:user_pk>/shift_confirmation/<int:year>/<int:month>/<int:day>/',views.Shift_ConfirmationView.as_view(),name='shift_confirmation'),

    path('shift_csv/<int:job_pk>/<int:year>/<int:month>/<int:day>/', views.Shift_csv.as_view(), name='shift_csv'),
    path('shift_csv/<int:job_pk>/', views.Shift_csv.as_view(), name='shift_csv'),
    path(
        'user/<int:user_pk>/submission_schedule/',
        views.SubmissionView.as_view(), name='submission_schedule'
    ),
    path(
        'user/<int:user_pk>/submission_schedule/<int:year>/<int:month>/<int:day>/',
        views.SubmissionView.as_view(), name='submission_schedule'
    ),
]

user/urls.py
from django.urls import path
from . import views
from .views import login_view

app_name='user'

urlpatterns = [
    # ... other URL patterns
   # path('', views.login_view, name='login'),
    #path('', views.CustomLoginView.as_view(), name='login'),
    path('', views.login_view, name='login'), 
    path('top/',views.Top.as_view(),name='top'),
    path('<int:pk>no/',views.MemberNo.as_view(),name='no'),
   

]

shift/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime
from django.utils import timezone
from django.conf import settings
from user.models import CustomUser

SUB_START = (
    
    ('1','6'),
    ('2','7'),
    ('3','8'),
    ('4','8.5'),
    ('5','9'),
    ('6','9.5'),
    ('7','10'),
    ('8','11'),
    ('9','12'),
    ('10','13'),
    ('11','13.5'),
    ('12','14'),
    ('13','14.5'),
    ('14','15'),
    ('15','15.5'),
    ('16','16'),
    ('17','16.5'),
    ('18','17'),
    ('19','17.5'),
    ('20','18'),
    ('21','18.5'),
    ('22','19'),

)
SUB_END = (
    
    ('1','8.5'),
    ('2','9'),
    ('3','11'),
    ('4','12'),
    ('5','13'),
    ('6','14'),
    ('7','14.5'),
    ('8','15'),
    ('9','15.5'),
    ('10','16'),
    ('11','16.5'),
    ('12','17'),
    ('13','18'),
    ('14','19'),
    ('15','20'),
    ('16','20.5'),
    ('17','21'),
    ('18','22'),



)

class Schedule(models.Model):
    """スケジュール"""
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.SET_NULL, blank=True, null=True,related_name = "user_schedule")
    start_time = models.CharField('開始時間', choices= SUB_START, max_length=50,blank=True,default=0)
    end_time = models.CharField('終了時間', choices= SUB_END, max_length=50,blank=True,default=0)
    date = models.DateField('日付')

    def __str__(self):
        return f"{self.user.user_name} {self.date}{self.start_time}"

shift/forms.py
from django import forms
from .models import Schedule
from crispy_forms.helper import FormHelper


class BS4ScheduleForm(forms.ModelForm):
    """Bootstrapに対応するためのModelForm"""

    class Meta:
        model = Schedule
        fields = ('start_time', 'end_time')
        widgets = {

            'start_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'end_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
        }

    def clean_end_time(self):
        start_time = self.cleaned_data['start_time']
        end_time = self.cleaned_data['end_time']
        if end_time <= start_time:
            raise forms.ValidationError(
                '終了時間は、開始時間よりも後にしてください'
            )
        return end_time


class ScheduleForm(forms.ModelForm):
    """シンプルなスケジュール登録用フォーム"""

    class Meta:
        model = Schedule
        fields = ('start_time', 'end_time', 'date')
        widgets = {
            # 'summary': forms.TextInput(attrs={
                # 'class': 'form-control',
            # }),
            'date': forms.HiddenInput,
            'shop':forms.HiddenInput,
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
                

shift/views.py
import datetime
from django.contrib.auth import get_user_model
from django.shortcuts import redirect, render, get_object_or_404
from django.views import generic
from .forms import BS4ScheduleForm, ScheduleForm
from .models import Schedule
from . import mixins
from .models import User
from user.models import CustomUser
from django.urls import reverse
from django.http import HttpResponse
import csv
#from openpyxl.writer.excel import save_virtual_workbook
import openpyxl as px
from openpyxl import worksheet
from openpyxl.utils import range_boundaries


User = get_user_model()

class Shift_top(generic.TemplateView):
      template_name = 'shift/shift_top.html'
        
class Shift_OutputView(mixins.Shift_OutputMixin, generic.TemplateView):
    
    model = Schedule
    template_name = 'shift/shift_list.html'
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        # shop = get_object_or_404(Shops, pk=self.kwargs['shops_pk'])
        # shop =self.kwargs['shops_pk']
        # context['shops']= User.objects.filter(shops__shop=shop)
        #bb=Shops.objects.all().order_by('shop')
        # c=[]
        # h=[]
        # b= 0
        # for a in bb:
        #     if a.shop in h:
        #         pass
        #     else:
        #         c.append(a)
        #         h.append(a.shop)
        # context['bshop']=c
        context['job_pk']=self.kwargs['job_pk']
        # shop=self.kwargs['shops_pk']
        # context['shop']=Shops.objects.filter(shop=shop)
        context.update(calendar_context)


        return context   

class Shift_csv(mixins.CsvMixin, generic.TemplateView):    
    model = Schedule
    template_name = 'shift/shift_csv.html'
    date_field = 'date'

    def get(self, request, **kwargs):
        context = self.get_context_data(**kwargs)
        # shop = get_object_or_404(Shops, pk=self.kwargs['shops_pk'])
        context['job_pk'] =self.kwargs['job_pk']
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        today = datetime.date.today()
        filename= today
        wb=context['wb']
        response = HttpResponse(content_type='application/vnd.ms-excel')
        # response = HttpResponse(save_virtual_workbook(wb), content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = 'attachment; filename={}.xlsx'.format(filename)
        wb.save(response)
        return response


class Shift_ConfirmationView(mixins.Shift_ConfirmationMixin, generic.TemplateView):
    """スケジュール付きの週間カレンダーを表示するビュー"""
    template_name = 'shift/shift_confirmation.html'
    model = Schedule
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = get_object_or_404(User, pk=self.kwargs['user_pk'])
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context



class SubmissionView(mixins.SubmissionMixin, generic.View):
    """フォーム付きの月間カレンダーを表示するビュー"""
    template_name = 'shift/submission_schedule.html'
    model = Schedule
    date_field = 'date'
    form_class = ScheduleForm

    def get(self, request, **kwargs):

        context = self.get_month_calendar()
        context['user'] = get_object_or_404(User, pk=self.kwargs['user_pk'])

        return render(request, self.template_name, context)
    

    def post(self, request, **kwargs):

        context = self.get_month_calendar()
        user_pk = self.kwargs['user_pk']
        user = get_object_or_404(User, pk=user_pk)
        context['user'] = user
        formset = context['month_formset']
        if formset.is_valid():

            instances = formset.save(commit=False)
            for schedule in instances:
                schedule.user = user
                schedule.end_at=schedule.get_end_time_display()
                schedule.start_at=schedule.get_start_time_display()
                user.schedule = schedule
                schedule.save()
                user.save()
            return redirect('shift:shift_confirmation', user_pk=user_pk)

        return render(request, self.template_name, context)

shift/templates/shift/shift_base.html
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

<head>
    
  <html lang="ja">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  
    </head>
 
    <nav class="navbar navbar-dark bg-dark  navbar-expand-lg " >
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
           
            <li class="nav-item">
              <a class="nav-link" >&nbsp;&nbsp;&nbsp;YES.{{user.user_name}}さん</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" >&nbsp;&nbsp;&nbsp;TOP</a>
            </li>  
              

           
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shift:submission_schedule' user.pk %}">提出</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shift:shift_confirmation' user.pk %}">確認</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shift:shift_list' 1%}">出力</a>
            </li>  
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:no' 1 %}">並べ替え</a>
            </li> 
            


        </div>
      </nav>
   
    
      
    </div>
  </nav>
  
      
     
            {% block content %}
        
        
            {% endblock %}
          </div>
        </div>
      </main>

       

      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

shift/templates/shift/shift_confirmation.html
{% extends "shift/shift_base.html" %}
{% block content %}


    <h5>{{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}</h5>

    <ul class="pagination">
        <li class="page-item"><a class="page-link" href="{% url 'shift:shift_confirmation' user.pk week_previous.year week_previous.month week_previous.day %}">前</a></li>
        <li class="page-item"><a class="page-link" href="{% url 'shift:shift_confirmation' user.pk week_next.year week_next.month week_next.day %}">次</a></li>
      </ul>

    <table class="table table-bordered"　>

        <tbody>
            {% for day,schedules in week_day_schedules.items %}
        <tr>
            
    <th><div class="text-center">{{day | date:"n"}}月{{day | date:"j" }}日 
    {% if day|date:"D" == "日" %}
      <small>
          <span style="color: #F00;">({{ day | date:"D" }})</span>
      </small></div></th>
      {% elif day|date:"D" == "土" %}
      <small>
            <span style="color:#0000FF">({{ day | date:"D" }})</span>
      </small></div></th>
      {% else %}
        <small>({{ day|date:"D" }})</small></div></th>
  
             {% endif %}
            </div>

       
            {% for s in schedules %}
            <td>   
     
            {{ s.get_start_time_display }} - {{ s.get_end_time_display }}</td>
            
            
                
            
        </tr>{% endfor %}{% endfor %}
        </tbody>
    </table>
       
        <a href="{% url 'shift:shift_top' %}" >
            <button type="submit" class="btn btn-primary">Ok</button></a>
    
    

{% endblock %}

shift/templates/shift/shift_csv.html
{% extends "shift/shift_base.html" %}
{% block content %}


{% load static %}

<!-- <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" /> -->


<style>
.mgr-10{
    margin-right : 100px;
}
    
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-link" href="{% url 'shift:shift_list' %}">全店</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
   
    </div>
  </nav>


<h3>{{ week_first}}-{{ week_last }}</h3>

<nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="{% url 'shift:shift_list'  week_previous.year week_previous.month week_previous.day %}">前</a></li>
      <li class="page-item"><a class="page-link" href="{% url 'shift:shift_list'  week_next.year week_next.month week_previous.day %}">次</a></li>
    </ul>
  </nav>

<table class="table table-bordered"　>
    <th>User</th>
    {% for day in df %}
    <th>{{day | date:"j" }}日<small>({{ day | date:"D" }})</small></th>
    {% endfor %}

    {% for index,row in df.iterrows %}

<tr>    
    <th>{{index}}</th>
    <td>{{row.0}}</td>
    <td>{{row.1}}</td>
    <td>{{row.2}}</td>
    <td>{{row.3}}</td>
    <td>{{row.4}}</td>
    <td>{{row.5}}</td>
    <td>{{row.6}}</td>
    <td>{{row.7}}</td>
    <td>{{row.8}}</td>
    <td>{{row.9}}</td>
    <td>{{row.10}}</td>
    <td>{{row.11}}</td>
    <td>{{row.12}}</td>
    <td>{{row.13}}</td>
    <td>{{row.14}}</td>
    
    {% if row.15 == True %}
    <td>{{row.15}}</td>
    {% else %}
    {% endif %}
</tr>

{% endfor %}
</table>

<div class="alert alert-primary" role="alert">
    csv出力しました<a href="#" class="alert-link"></a>
  </div>
  
        <!-- <a href="{% url 'shift:submission_schedule' user.pk %}" >
        <button type="submit" class="btn btn-primary">Turn Back</button></a>
        <a href="{% url 'register:top' %}" >
            <button type="submit" class="btn btn-primary">Ok</button></a> -->
    
    

{% endblock %}

shift/templates/shift/shift_list.html
{% extends "shift/shift_base.html" %}
{% block content %}


{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
<title>シフト</title>

<!-- <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" /> -->


<style>
.mgr-10{
    margin-right : 100px;
}
    
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light" >
  <a class="navbar-link" href="{% url 'shift:shift_list' 1 %}">   EDW　　
  </a>
  <a class="navbar-link" href="{% url 'shift:shift_list' 2 %}">   OHB
  </a>
  <a class="navbar-link" href="">{{get_user_job_display}}
  </a>
 
</nav>
<nav class="navbar navbar-expand-lg navbar-light bg-light" >
 
  <span class="nav-item">
    <a class="nav-item nav-link" href="{% url 'shift:shift_list' job_pk week_previous.year week_previous.month week_previous.day %}">先月<<<</a>
  </span>

  <span class="nav-item">
    <a class="nav-item nav-link"href="{% url 'shift:shift_list' job_pk week_next.year week_next.month week_next.day %}">>>>次月</a>
  </span>
</nav>

<div class="table-responsive">
  <table class="table table-bordered table-sm"　>

  <th><div class="text-center">User</div></th>
  {% for day in df %}
    <th><div class="text-center">{{day | date:"n"}}月{{day | date:"j" }}日 <br>
      {% if day|date:"D" == "日" %}
        <small>
            <span style="color: #F00;">({{ day | date:"D" }})</span>
        </small></div></th>
        {% elif day|date:"D" == "土" %}
        <small>
              <span style="color:#0000FF">({{ day | date:"D" }})</span>
        </small></div></th>
        {% else %}
          <small>({{ day|date:"D" }})</small></div></th>
    
               {% endif %} {% endfor %}

{% for index,row in df.iterrows %}


{% if index == "必要人数" %}

<tr>    
  <td bgcolor="#EEEEEE"><small><div class="text-center">{{index}}</div></small></td>
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.0}}</div></small></td>
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.1}}</div></small></td>
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.2}}</div></small></td>
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.3}}</div></small></td>
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.4}}</div></small></td>
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.5}}</div></small></td>
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.6}}</div></small></td>
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.7}}</div></small></td>
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.8}}</div></small></td>
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.9}}</div></small></td>
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.10}}</div></small></td>
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.11}}</div></small></td>
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.12}}</div></small></td>
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.13}}</div></small></td>
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.14}}</div></small></td>
  {% if row.15 == None %}
  
  {% else %}
  
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.15}}</div></small></td>
  {% endif %}
</tr>
{% elif index == "過不足"%}

<tr>    
  <th bgcolor="#EEEEEE"><small><div class="text-center">{{index}}</div></small></th>
  {% if row.0 < 0 %}
  <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.0}}</div></small></td>
  {% else %}
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.0}}</div></small></td>
  {% endif %}
  {% if row.1 < 0 %}
  <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.1}}</div></small></td>
  {% else %}
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.1}}</div></small></td>
  {% endif %}
  {% if row.2 < 0 %}
  <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.2}}</div></small></td>
  {% else %}
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.2}}</div></small></td>
  {% endif %}
  {% if row.3 < 0 %}
  <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.3}}</div></small></td>
  {% else %}
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.3}}</div></small></td>
  {% endif %}
  {% if row.4 < 0 %}
  <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.4}}</div></small></td>
  {% else %}
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.4}}</div></small></td>
  {% endif %}
  {% if row.5 < 0 %}
  <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.5}}</div></small></td>
  {% else %}
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.5}}</div></small></td>
  {% endif %}
  {% if row.6 < 0 %}
  <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.6}}</div></small></td>
  {% else %}
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.6}}</div></small></td>
  {% endif %}
  {% if row.7 < 0 %}
  <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.7}}</div></small></td>
  {% else %}
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.7}}</div></small></td>
  {% endif %}
  {% if row.8 < 0 %}
  <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.8}}</div></small></td>
  {% else %}
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.8}}</div></small></td>
  {% endif %}
  {% if row.9 < 0 %}
  <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.9}}</div></small></td>
  {% else %}
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.9}}</div></small></td>
  {% endif %}
  {% if row.10 < 0 %}
  <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.10}}</div></small></td>
  {% else %}
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.10}}</div></small></td>
  {% endif %}
  {% if row.11 < 0 %}
  <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.11}}</div></small></td>
  {% else %}
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.11}}</div></small></td>
  {% endif %}
  {% if row.12 < 0 %}
  <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.12}}</div></small></td>
  {% else %}
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.12}}</div></small></td>
  {% endif %}
  {% if row.13 < 0 %}
  <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.13}}</div></small></td>
  {% else %}
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.13}}</div></small></td>
  {% endif %}
  {% if row.14 < 0 %}
  <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.14}}</div></small></td>
  {% else %}
  <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.14}}</div></small></td>
  {% endif %}
  
  {% if row.15 == None %}
  {%else%}
     {% if row.15 < 0 %}
     <td  bgcolor="#ff7f50"><small><div class="text-center">{{row.15}}</div></small></td>
     {% else %}
     <td  bgcolor="#EEEEEE"><small><div class="text-center">{{row.15}}</div></small></td>
  {% endif %}
  {%endif%}
 
</tr>
{% else %}
<tr>
  <th><div class="text-center">{{index}}</div></th>
  <td><div class="text-center">{{ row.0}}</div></td>
    <td><div class="text-center">{{row.1}}</div></td>
    <td><div class="text-center">{{row.2}}</div></td>
    <td><div class="text-center">{{row.3}}</div></td>
    <td><div class="text-center">{{row.4}}</div></td>
    <td><div class="text-center">{{row.5}}</div></td>
    <td><div class="text-center">{{row.6}}</div></td>
    <td><div class="text-center">{{row.7}}</div></td>
     <td><div class="text-center">{{row.8}}</div></td>
     <td><div class="text-center">{{row.9}}</div></td>
     <td><div class="text-center">{{row.10}}</div></td>
     <td><div class="text-center">{{row.11}}</div></td>
     <td><div class="text-center">{{row.12}}</div></td>
     <td><div class="text-center">{{row.13}}</div></td>
     <td><div class="text-center">{{row.14}}</div></td>

     {% if row.15 == None %}
     {%else%}
     <td><div class="text-center">{{row.15}}</div></td>
     {%endif%}

    
</tr>
{% endif %}
{% endfor %}


</table></div>
{% for day in df %}
    {% if forloop.first %}
    
    <a href="{% url 'shift:shift_csv' job_pk day.year day.month day.day %}" class="btn btn-info btn-block login"><img src="{% static 'images/xlsx.png' %}" width="25" height="25"  class="d-inline-block align-top" alt="">&nbsp; 出力</a>
    {% else %}
    {% endif %}
{% endfor %}    
    
    

{% endblock %}

shift/templates/shift/shift_top.html

{% extends "shift/shift_base.html" %}
{% block content %}
----------------information-----------------------
シフト提出



{% endblock %}

